sudo: false
language: elixir
env:
  - MPOWER_MASTER_KEY="5b9f531a-fbb8-487a-8045-3b4c7ac5acee"
  - MPOWER_PRIVATE_KEY="test_private_3NgIe4eR98bA3JvDn_zBCWnnSZE"
  - MPOWER_TOKEN="2f55bc094d9898292975"
before_script:
  - mix deps.get
script:
  - mix test
